// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantServiceProvider;

namespace RestaurantServiceProvider.Migrations
{
    [DbContext(typeof(RestaurantServiceProviderContext))]
    partial class RestaurantServiceProviderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestaurantServiceProvider.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPersons")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RestaurantServiceProvider.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RestaurantServiceProvider.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("903a213a-7f14-4075-9ea4-d6fecd2b6c37"),
                            Address = "Bld. Tudor Vladimirescu, et.2",
                            Description = "Clatite americane reinventate, arome delicioase",
                            Name = "Panck's"
                        },
                        new
                        {
                            Id = new Guid("e6f8a0ca-1c18-49ba-8965-899dde583528"),
                            Address = "Bld. Carol I nr.4 ",
                            Description = "Va asteptam intr-o ambianţă originală, cu puternice accente tradiţionale moldoveneşti si cu un meniu foarte atractiv.",
                            Name = "La Placinte"
                        },
                        new
                        {
                            Id = new Guid("35c21d36-8a1a-4cf5-82c6-ee807c632374"),
                            Address = "Strada Silvestru nr. 4, Iași 700259",
                            Description = "Culoarea are gust.",
                            Name = "Oliv"
                        },
                        new
                        {
                            Id = new Guid("6d6cb2e2-e68c-46ef-b598-502ecce8beca"),
                            Address = "3F, Strada Palas, Iași 700032",
                            Description = "Sophisticated and tempting restaurant. Located in the historic core of the city, near the Palace of Culture in the Palas ensemble which is \"city in the heart of the city\".Elegant interior and luxurious atmosphere.",
                            Name = "Fenice"
                        },
                        new
                        {
                            Id = new Guid("4da203dd-e6b6-43bf-9597-55a99faeadba"),
                            Address = "Palas Food Court, Strada Palas 5C, Iași 700259",
                            Description = "Puterea gustului!",
                            Name = "Mado Palas"
                        },
                        new
                        {
                            Id = new Guid("d16a59d6-b738-46c5-81f7-b62804d8fc38"),
                            Address = "Esplanada Teatrul Luceafărul, Iași 700259",
                            Description = "The Trumpets este locul în care, lăsănd grijile la o parte, se amplifică simțurile și deschiderea către distracție. Auzul, gustul, simțul olfactiv și cel tactil, sunt celebrate în cadrul pub-ului pentru a-ți reda buna dispoziție după ce ai petrecut o zi cu ochii în calculator, rapoarte sau facturi. Fiindcă cercetătorii britanici au descoperit că partea plină a paharului se vede cel mai bine atunci când iți aduce chelnerul următorul rând.",
                            Name = "The Trumpets"
                        },
                        new
                        {
                            Id = new Guid("8bb5e343-4c5e-46ec-9b7a-0d1a8c56f33d"),
                            Address = "Strada Palat 3F, Iași 700032",
                            Description = "Grilling to perfection is not a goal it's a MUST!",
                            Name = "Chef Galerie"
                        },
                        new
                        {
                            Id = new Guid("100f3c09-41ff-4a7c-971d-94efcf67c8df"),
                            Address = "Strada Grigore Ureche nr. 27, Iași 700044",
                            Description = "Legend este locul unde berea e mai rece decât ți-ai putea imagina, mâncarea este mai bună decât atunci când nu mai poți de foame, iar petrecerile sunt mai nebune decât orice-ai văzut înainte. De ce? Fiindcă trăim totul la superlativ. Despre asta este #Legend",
                            Name = "Legend Pub"
                        },
                        new
                        {
                            Id = new Guid("20ba02d8-8115-43ae-85d6-6553b0e270ff"),
                            Address = "Shopping Street, Iași 700051",
                            Description = "Pentru că prietenii merg mână în mână cu un cocktail bun, cafeaua italiană merge perfect cu diminețile pline de soare și weekendurile nu sunt la fel fără o masă cu savori italiene alese, alături de familie, s-a creat C-House!",
                            Name = "C House Lounge"
                        },
                        new
                        {
                            Id = new Guid("11831525-8ed3-4f5b-8029-22cb04ef2f7a"),
                            Address = "Strada Palas",
                            Description = "Construit dintr-o idee grozavă și nu liniștită, Treaz & Nu este primul local conceptual din oraș menit să-i gâdile pe iubitorii de vinuri și pasionații de cafea.Credem că pe lume există prea puțină cafea de specialitate și vinuri de calitate, pentru câte lucruri avem să ne spunem. Așa că hai să le-ncercăm pe toate!",
                            Name = "Treaz & Nu"
                        },
                        new
                        {
                            Id = new Guid("a783b5ac-5cdf-4db6-b706-af7b4401187d"),
                            Address = "Strada Palas nr. 7A, Iași 700051",
                            Description = "Carbon a fost creat pentru a redefini experienta gastronomica.",
                            Name = "Carbon"
                        });
                });

            modelBuilder.Entity("RestaurantServiceProvider.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93bd6f45-e890-4453-8856-1e9033855137"),
                            Email = "tudormanoleasa@gmail.com",
                            FirstName = "Tudor",
                            LastName = "Manoleasa",
                            Password = "parolatudormanoleasa"
                        },
                        new
                        {
                            Id = new Guid("a25e2a4e-895c-4072-889a-58c313fd49e3"),
                            Email = "roxana.apopei@yahoo.com",
                            FirstName = "Roxana",
                            LastName = "Apopei",
                            Password = "parolaroxanaapopei"
                        });
                });

            modelBuilder.Entity("RestaurantServiceProvider.Entities.Booking", b =>
                {
                    b.HasOne("RestaurantServiceProvider.Entities.Product", null)
                        .WithMany("Bookings")
                        .HasForeignKey("ProductId");

                    b.HasOne("RestaurantServiceProvider.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantServiceProvider.Entities.Product", b =>
                {
                    b.HasOne("RestaurantServiceProvider.Entities.Booking", null)
                        .WithMany("Products")
                        .HasForeignKey("BookingId");

                    b.HasOne("RestaurantServiceProvider.Entities.Restaurant", "Restaurant")
                        .WithMany("Products")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
